### ISSUE TITLE
beta3 addSubscription 

### ISSUE THREAD

**Issue by istvanskeri** [Brulath/fitbit-php-oauth2#10]
In the addSubscription function i noticed that the post function call is being called incorrectly. First param should be "POST"

**Comment by bjvandrews** [comment]
``` php
    public function addSubscription($id, $path = null, $subscriberId = null, $delete_existing_subscriptions = false) {
        if ($delete_existing_subscriptions) {
            $this->deleteExistingSubscriptions();
        }
        $userHeaders = array();
        if ($subscriberId) {
            $userHeaders['X-Fitbit-Subscriber-Id'] = $subscriberId;
        }
        $path = !empty($path) ? "/{$path}" : '';

        return $this->post("user/-" . $path . "/apiSubscriptions/" . $id, null, null, $userHeaders);
    }
```

Are you referring to this code or an older version? I don't quite follow

**Comment by istvanskeri** [comment]
yes the above function  should return 

 return $this->post("POST", "user/-" . $path . "/apiSubscriptions/" . $id, null, null, $userHeaders);

**Comment by bjvandrews** [comment]
Ah yep, it required the direct call because of the extra header. Should be fixed in beta4. Thanks :)
