### ISSUE TITLE
Command line and sessions

### ISSUE THREAD

**Issue by istvanskeri** [Brulath/fitbit-php-oauth2#13]
I've written a amqp php worker script that uses this library to harvest Fitbit subscription messages from Rabbitmq. I noticed that you are using sessions for an edge case in this library. If i run the script command line will sessions still work?

**Comment by bjvandrews** [comment]
You should be able to use the library from the command line successfully to collect data for any user you already possess authentication tokens for (I do this). The sessions are only used for acquiring tokens and, iirc, are optional.
