### ISSUE TITLE
Refresh Token Expires

### ISSUE THREAD

**Issue by istvanskeri** [Brulath/fitbit-php-oauth2#14]
For a small percent of users i am seeing refresh tokens expired exception. Does anyone have any insight on how this is happening??

**Comment by istvanskeri** [comment]
I am also noticing 502 and 504 responses from fitbit for a small percentage of my calls. I wonder if these errors are related to the expired refresh token problem.

**Comment by bjvandrews** [comment]
This particular code base doesn't perform an action that would expire your refresh token, perhaps Fitbit does that. Maybe try their development forums?
