### ISSUE TITLE
Fatal error: Interface 'Sabre\Event\EventEmitterInterface' not found

### ISSUE THREAD

**Issue by desmeit** [Brulath/fitbit-php-oauth2#15]
Hi,

how could I embed the oauth2 library?
It seems it is missing.

I embed fitbit-php-oauth2 with this code:

`require ABSPATH . 'wp-content/plugins/fitbit/fitbit-php-oauth2/src/FitbitPHPOAuth2.php';`

but I get the error:

`Fatal error: Interface 'Sabre\Event\EventEmitterInterface' not found`

How is it working?

Thanks

**Comment by bjvandrews** [comment]
That is not a sufficient approach to embed the library into a page; you'll need to look into how to use composer (see the [dependencies this library has](https://github.com/Brulath/fitbit-php-oauth2/blob/master/composer.json)) or include the remaining libraries manually yourself.

**Comment by desmeit** [comment]
Thanks. Could you give an example to embed with composer?

**Comment by bjvandrews** [comment]
Create a json file like this called composer.json in the root directory:

```
{
    "name": "myapp",
    "require": {
        "league/oauth2-client": "^1.3",
	"brulath/fitbit-php-oauth2": "@dev"
    },
    "config": {
        "vendor-dir": "Vendor/"
    }
}
```

run ```composer install``` to install the dependencies into the Vendor/ directory.

In the relevant file, import:
```require_once([YOUR ROOT DIRECTORY] . 'Vendor/brulath/fitbit-php-oauth2/src/fitbit-php-oauth2.php');```

Might work :)

**Comment by desmeit** [comment]
Thank you very much. :-)
