### ISSUE TITLE
Missing return & not working via composer

### ISSUE THREAD

**Issue by williamsdb** [Brulath/fitbit-php-oauth2#2]
Hi

There is a bug, I think, in the following. Think it needs a return before the $this...

```
   public function getFoods($date) {
        $this->read("user/-/foods/log/date/" . $date);
    }
```

Also I have not been able to get this to work when loading via composer, I get the following:

```
Fatal error: Class 'brulath\fitbit\FitBitPHPOauth2' not found 
```

Other packages loaded via composer works fine and this works ok if loaded directly but not via composer. Any ideas?

**Comment by bjvandrews** [comment]
Hey, I think I fixed the getFoods and the composer installation. I'm not entirely sure what the deal is with the autoloader not working; as far as I can tell I just have to specify autoload but it's ignoring it. Might have to look into it a bit further :)

**Comment by williamsdb** [comment]
Hi, thanks for the quick response. I spent a couple of hours on Sunday trying to figure the issue out but couldn't so switched to loading it directly which works great. However, would be better to be able to load via composer.

**Comment by bjvandrews** [comment]
Hey, solved the composer issue; apparently the file name is important and renaming it to match the main class allows auto-loading to find it. Installing via composer should probably work correctly now (at least this small test script doesn't throw errors, anyway). Hope that helps :)

```
<?php
require_once('./vendor/autoload.php');
use brulath\fitbit;

$API = new brulath\fitbit\FitBitPHPOauth2(
        'client_id',
        'client_secret',
        'redirect_uri',
        ['activity', 'nutrition', 'profile', 'settings', 'sleep', 'social', 'weight'],
        true,  // debug,
        true, // Auto request
        true // auto refresh
);
```

**Comment by williamsdb** [comment]
Hi Bruce

Yes that does indeed seem to work although I now have another issue…

Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Failed: 400 {}' in /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php:1355 Stack trace: #0 /var/www/html/neilatwork/fitbit/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(644): brulath\fitbit\FitbitProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /var/www/html/neilatwork/fitbit/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(560): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) #2 /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php(116): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken('refresh_token', Array) #3 /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php(1168): brulath\fitbit\FitBitPHPOauth2->refresh_token() #4 /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPH in /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php on line 1355

This seems to be when refreshing the token. The error returned from Fitbit is Bad Request but I can’t see how to find the error text returned to go with this nor the request that is being sent. Do you know how I can find that so I can see where my issue lies?

Thanks 

              

On 4 August 2016 at 15:07:20, Bruce Andrews (notifications@github.com) wrote:

Closed #2.

**Comment by bjvandrews** [comment]
You could probably try replacing `json_encode($response)` with `$response->getReasonPhrase()` on line 1355 in FitBitPHPOauth2.php and see if the response generated is more useful (presumably the problem is json serialising the class doesn't actually retrieve the message).

It will probably produce one of [these errors](https://dev.fitbit.com/docs/oauth2/#authorization-request-errors) if it shows up. The `ResponseInterface` is defined in `Psr\Http\Message\ResponseInterface`.

**Comment by williamsdb** [comment]
Hi

Actually already done that and that just gives: Failed: 400 Bad Request not not the more details (and more useful message) that I can use to diagnose.

              

On 4 August 2016 at 15:31:18, Bruce Andrews (notifications@github.com) wrote:

You could probably try replacing json_encode($response) with $response->getReasonPhrase() on line 1355 in FitBitPHPOauth2.php and see if the response generated is more useful (presumably the problem is json serialising the class doesn't actually retrieve the message).

It will probably produce one of these errors if it shows up. The ResponseInterface is defined in Psr\Http\Message\ResponseInterface.

**Comment by bjvandrews** [comment]
try `getResponseBody()` on [the exception](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/Exception/IdentityProviderException.php)?

**Comment by williamsdb** [comment]
OK so I think that line 1354 in your code would be better as:

            $message = "Failed: " . $response->getStatusCode() . " " . json_encode($data);

than:

            $message = "Failed: " . $response->getStatusCode() . " " . json_encode($response);

As $data has the info you really need:

Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Failed: 400 {"errors":[{"errorType":"invalid_grant","message":"Refresh token invalid: e5b18e501c71e24920cd70006e1cb45a8f280cdaf7c0d73b67e1b4d4091a8672. Visit https:\/\/dev.fitbit.com\/docs\/oauth2 for more information on the Fitbit Web API authorization process."}],"success":false}' in /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php:1355 Stack trace: #0 /var/www/html/neilatwork/fitbit/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(644): brulath\fitbit\FitbitProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /var/www/html/neilatwork/fitbit/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(560): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) #2 /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php(116): League\OAuth2\Client\Provider\AbstractProvider in /var/www/html/neilatwork/fitbit/vendor/brulath/fitbit-php-oauth2/src/FitBitPHPOauth2.php on line 1355

Now I know what the issue is I can perhaps fix my code!

Thanks for your help.

              

On 4 August 2016 at 15:54:49, Bruce Andrews (notifications@github.com) wrote:

try getResponseBody() on the exception?

**Comment by bjvandrews** [comment]
Awesome, thanks :)
