### ISSUE TITLE
Separate classes into separate files?

### ISSUE THREAD

**Issue by starJammer** [Brulath/fitbit-php-oauth2#3]
Is there any intent here to separate all the classes into their own files and follow PSR standards? Also, you copied the djchen/oauth2-fitbit files directly into your project when you didn't have to. 

I can happily submit a merge request for this if you want.

**Comment by starJammer** [comment]
oh right, i see why you copied them. Either way, I'll submit a pull request and leave it up to you if you like the changes.

**Comment by bjvandrews** [comment]
I merged it in and version bumped to deal with the API change. Modified the Oauth to be OAuth as well, as that's how the Fitbit docs refer to it.

Thanks for the cleanup :)
