### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by starJammer** [Brulath/fitbit-php-oauth2#5]
Hey, it seems like you're actively developing this now from the recent activity and quick response.

I'm facing an issue in my development group where we have to migrate to OAuth2 with Fitbit. I'm hoping to be able to use this instead of developing one in house from scratch. However, it has to happen quickly on our side. I already have a fork of this and will continue to make pull requests/alterations. I'll leave it up to you to decide what happens ultimately.

Thanks for starting this and I hope we can collaborate some more.

**Comment by starJammer** [comment]
Hey Brulath, 

just a heads up on some things. In your example of making an API call you have 

```
$activities = $fitbit->getActivities('2016-02-20');
storeAccessTokenIfItChanged($fitbit->getToken());
```

but I think there's a better way to have the class notify anyone that the token has actually failed and been updated. I'll be submitting an MR for it. I'll try to make it so that it is backward compatible.

**Comment by bjvandrews** [comment]
Hey :)

The storeAccessTokenIfItChanged thing is something I added quickly when I encountered an unexpected token refresh myself, so I haven't put much thought into it; if you have then that's awesome :)

I think breaking changes are fine; whenever the API changes I'll just bump the major version number as a warning. It's a pretty simple library interface, so it shouldn't be too much bother to follow the changes on rare occasion that one updates their composer file.

**Comment by mycodecrafting** [comment]
Hey Brulath,

@starJammer and I have our solution for the unexpected token refresh in Pull request #7

**Comment by bjvandrews** [comment]
Hey, thanks for that. I've merged that in, as well as making it fire on oauth1 token promotion.

Other stuff changed (bumped to 3.0.0-beta1):
- changed the constructor to use an options array, to make it easier to add stuff in the future
- added the logger to the API class
- changed the API class's doAuthFlow method so it's possible to perform the two steps manually
- wrapped exceptions so getMessage() returns json_encoded errors array
- updated readme

**Comment by starJammer** [comment]
Hey! Glad you're still doing dev work on this.

I couldn't comment directly on the diff, I don't know why. Probably because it's just a commit instead of a PR.

Anyway,

In this diff, https://github.com/Brulath/fitbit-php-oauth2/compare/320b239a69...562ee265a7#diff-4279b44a6bd669137894114ddd64708eR1249

in `src/FitbitPHPOAuth2.php:1249`, you have `return $this->refreshToken()` and on line 1222 you do `if ($this->handleRequestError($e)) {`, but return token doesn't return anything and the if statement will evaluate to false and won't auto refresh the token. At least, that's what I see. We haven't updated to this version so I can't test directly yet.

**Comment by bjvandrews** [comment]
True, good catch. I don't think that code would work at all anyway, though, as the token is used to created headers in the `$this->provider->getAuthenticatedRequest('DELETE', $path, $this->access_token, $params)` call. I'll have to move that call into processRequest in order to update the headers with the new token in a consistent manner.

**Comment by bjvandrews** [comment]
Removed the refresh token handling, as we were refreshing the tokens [if expired] before making a request anyway. Moved the code together in a function to make that more obvious.

**Comment by istvanskeri** [comment]
Couple of Questions:

At what point will this event trigger:

$fitbit->on('refresh-token', <your_token_saving_function>);

in my token saving function do i need to call getToken() and save the tokens to the db?

After I make a call to get activities, how come when i call getToken again I don't see a new refresh token? I thought after every request there is a new refresh token.

**Comment by starJammer** [comment]
@istvanskeri, the tokens are refreshed only in two cases
1. The timestamp on the token is in the past
2. The API responds with a response saying the token is expired.

Otherwise, no, the token is not refreshed in each request. That isn't necessary.

**Comment by starJammer** [comment]
@istvanskeri,

The documentation isn't clear. The events are generated like this 

```
$this->emit('obtain-token', [ $token ]);
$this->emit('refresh-token', [ $token ]);
```

`$token` is an `AccessToken` from the league library. Your event handler should look a little something like this

```
$fb->on('refresh-token', function (AccessToken $token) {
//Code to save to the db
});
```

**Comment by starJammer** [comment]
@istvanskeri, please submit a pull request to the documentation if you like.

**Comment by bjvandrews** [comment]
Hey, fixed that bug; events now return the same array as getToken(), which is json-serializable. You should pass that array to setToken or the constructor (and store it somewhere as the oauth2 token). Updated the documentation to clarify a bit.

**Comment by starJammer** [comment]
@Brulath I would prefer the use of the `AccessToken` object directly. I don't feel like there is a need to serialize it when it's being passed around in code. Not that it's too relevant but IDEs will also have an easier time providing help with what methods are available. The serialized array is fine as well but it's more prone to error since the language can't verify that the keys you use are correct. However, with the object, the php interpreter will let you know you typed the method name incorrectly.

**Comment by bjvandrews** [comment]
Added the option to specify that you'd prefer the AccessToken to be returned/emitted instead of the json-serialised version (which is the default, because it was the default accepted by setToken and the least effort for a user to deal with if they don't care about its contents).

**Comment by istvanskeri** [comment]
Is there any way to catch the exceptions generated in FitbitPHPOAuth2.php's handleRequestError and display my own error messaging? Also, does the logger log exception errors?

**Comment by istvanskeri** [comment]
I've set up a subscription service using your library. When looking at the subscription logs on the fitbit site i see that i have 95% success rate at my subscription endpoint. I am getting 500 sometimes. After doing some debugging I noticed that the last message from my debugger is "error_recovery"

From doing some research i realized that when calling getActivities it called it with expired token, so your library is attempting to do a refresh token which I believe is successful. 

What I don't see is another attempt to call the subscription one more time after the token is refreshed. My question is the following:

If my tokens are expired and I call getActivities, will it try to getActivities one more time or do i have to do that manually?

**Comment by bjvandrews** [comment]
Hey, as noted in #9 the logic regarding retrying requests was flawed and has been removed in the latest beta, as token refreshes are attempted before requests so capturing expiration exceptions and retrying is pointless (as there's theoretically some other issue at that point) :)
