### ISSUE TITLE
no return value for function refreshToken 

### ISSUE THREAD

**Issue by istvanskeri** [Brulath/fitbit-php-oauth2#9]
There is no return value for refreshToken function so processRequest will never try the request again and is throwing an exception. 

See line 1223 in FitbitPHPOAuth2.php. 

handleRequestError function returns refreshToken and it will always be null. 

I noticed this issue when when my subscription endpoint failed 5% of the time.

**Comment by bjvandrews** [comment]
Ah yes, I noticed the entire system for retrying was flawed and abandoned it in the beta versions. The system should be attempting to refresh the token if it's expired before attempting to make any calls to the API. The original version wasn't going to achieve the correct outcome for some reason which I forget now :)

**Comment by istvanskeri** [comment]
Would you recommend that i do the refresh manually based on the token expires data that Im saving to the database?

**Comment by bjvandrews** [comment]
It looks like you're using 3.0.0-beta1 as your version, which contains a function I experimented with then abandoned. beta3 should exclude that function entirely; each request will check whether the token needs refreshing, refresh it if necessary, then execute the request and throw a FitbitException if it fails. Theoretically these failures wouldn't be refresh-related, unless you disabled automatic token refreshing when instantiating the api object. You could certainly add code to double-check the expiration time on the tokens though :)

**Comment by istvanskeri** [comment]
is this the latest version? 

 "brulath/fitbit-php-oauth2": "3.0.0-beta3"

**Comment by bjvandrews** [comment]
Yeah. It shouldn't contain that handleRequestError function.

**Comment by istvanskeri** [comment]
ok great thanks
